import { Lato } from 'next/font/google';
import "@/styles/globals.css";
import ThankYouHeader from '@/components/layouts/thank-you/ThankYouHeaders';

const lato = Lato({
    weight: '400',
    subsets: ['latin'],
    variable: '--font-lato',
})


//TODO descomentar metadata cuando se tenga el contenido tomado desde contentful

/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function CheckoutLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={lato.className}>
            <ThankYouHeader />
            {children}
        </div>
    );
}