import Footer from "@/components/molecules/footer";
import Navigation from "@/components/molecules/navigation";
import { Lato } from "next/font/google";

const lato = Lato({subsets: ['latin'], weight:['400', '700']})

//TODO descomentar metadata cuando se tenga el contenido tomado desde contentful

/*export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};*/

export default function MainLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={lato.className}>
            <Navigation />
            {children}
            <Footer />
        </div>
    )
}