import Footer from "@/components/molecules/footer";
import Navigation from "@/components/molecules/navigation";
import { Lato } from "next/font/google";

const lato = Lato({
    weight: '400',
    subsets: ['latin'],
    variable: '--font-lato',
})


//TODO descomentar metadata cuando se tenga el contenido tomado desde contentful

/*export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};*/

export default function MainLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es" className={`${lato.variable}`}>
            <body>
                <Navigation />
                {children}
                <Footer />
            </body>
        </html>
    )
}