import "@/styles/globals.css";
import { Lato } from "next/font/google";
import NavigationLanding from "@/components/molecules/navigationLandingComponent";
const lato = Lato({ subsets: ['latin'], weight: ['400', '700'] })
import FooterLandingContent from "@/components/molecules/footerLandingComponent";


//TODO descomentar metadata cuando se tenga el contenido tomado desde contentful

/*export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};*/

export default function CheckoutLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={lato.className}>
            {/* header de las landing */}
            <NavigationLanding />
            {children}
            {/* footer de las landing */}
            <FooterLandingContent />
        </div>
    );
}