export const CodigosCFDI = [
    { key: "G01", label: "G02 - Adquisición de mercancías" },
    { key: "G02", label: "G02 - Devoluciones, descuentos o bonificaciones" },
    { key: "G03", label: "G03 - Gastos en general" },
    { key: "101", label: "101 - Construcciones" },
    { key: "102", label: "102 - Mobiliario y equipo de oficina para inversiones" },
    { key: "103", label: "103 - Equipo de transporte" },
    { key: "104", label: "104 - Equipo de computo y accesorios" },
    { key: "105", label: "105 - Dados, troqueles, moldes, matrioces y herramental" },
    { key: "106", label: "106 - Comunicaciones telefónicas" },
    { key: "107", label: "107 - Comunicaciones satelitales" },
    { key: "108", label: "108 - Otra maquinaria y equipo" },
    { key: "D01", label: "D01 - Honorarios médicos, dentales y gastos hospitalarios" },
    { key: "D02", label: "D02 - Gastos médicos por incapacidad o discapacidad" },
    { key: "D03", label: "D03 - Gastos funerarios" },
    { key: "D04", label: "D04 - Donativos" },
    { key: "D05", label: "D05 - Intereses reales efectivamente pagados por créditos hipotecarios" },
    { key: "D06", label: "D06 - Aportaciones voluntarias al SAT" },
    { key: "D07", label: "D07 - Primas por seguros de gastos médicos" },
    { key: "D08", label: "D08 - Gastos de transportación escolar obligatoria" },
    { key: "D09", label: "D09 - Depósitos en cuentas para el ahorro" },
    { key: "D10", label: "D10 - Pagos por servicios educativos (colegiaturas)" },
    { key: "S01", label: "S01 - Sin efectos fiscales" },
    { key: "CP01", label: "CP01 - Pagos" },
    { key: "CN01", label: "CN01 - Nómina" }
]

export const RegimenFiscal = [
    { key: "601", label: "601 - General de Ley PErsonas Morales" },
    { key: "605", label: "605 - Sueldos y Salarios e Ingresos Asimilados a Salariados" },
    { key: "606", label: "606 - Arrendamiento" },
    { key: "607", label: "607 - Regimen de Enajenación o Adquisición de Bienes" },
    { key: "608", label: "608 - Demás ingresos" },
    { key: "610", label: "610 - Residentes en el Extranjero sin Establecimiento Permanente en México" },
    { key: "611", label: "611 - Ingresos por Dividentos (socios y accionistas)" },
    { key: "612", label: "612 - Personas Fisicas con Actividades Empresariales y Profesionales" },
    { key: "614", label: "614 - Ingresos por intereses" },
    { key: "615", label: "615 - Régimen de los ingresos por obtención de premios" },
    { key: "616", label: "616 - Sin obligaciones fiscales" },
    { key: "620", label: "620 - Sociedades Cooperativas de Producción que Optan por Diferir sus Ingresos" },
    { key: "621", label: "621 - Incorporación Fiscal" },
    { key: "622", label: "622 - Actividades Agrícolas, Ganaderas, Silvícolas y Perqueras PM" },
    { key: "624", label: "624 - Coordinados" },
    { key: "625", label: "625 - Régimen de las Actividades Empresariales con Ingresos a Través de Plataformas Tecnológicas" },
    { key: "626", label: "626 - Régimen Simplificado de Confianza" },
]