import { Lato } from 'next/font/google';
import "../styles/globals.css";
import { IzziProvider } from '@/components/providers/IzziProvider';
import { ScrollReset } from '@/utils/scroll-reset';


const lato = Lato({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-lato',
})

//TODO descomentar metadata cuando se tenga el contenido tomado desde contentful

/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={`${lato.variable}`}>
      <body>
        <IzziProvider>
          <ScrollReset />
          {children}
        </IzziProvider>
      </body>
    </html>
  );
}
