import { Lato } from 'next/font/google';
import "../styles/globals.css";
import { IzziProvider } from '@/utils/IzziProvider';


const lato = Lato({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-lato',
})
export const revalidate = 900;
//TODO descomentar metadata cuando se tenga el contenido tomado desde contentful

/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={`${lato.variable}`}>
      <body>
        <IzziProvider>
        {children}
        </IzziProvider>
      </body>
    </html>
  );
}
